// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StargateAPI.Business.Data;

#nullable disable

namespace StargateAPI.Migrations
{
    [DbContext(typeof(StargateContext))]
    [Migration("20251006232511_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CareerEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CareerStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentDutyTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("AstronautDetail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareerStartDate = new DateTime(2020, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Commander",
                            CurrentRank = "1LT",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            CareerStartDate = new DateTime(1969, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Commander",
                            CurrentRank = "LCL",
                            PersonId = 3
                        },
                        new
                        {
                            Id = 3,
                            CareerEndDate = new DateTime(1969, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CareerStartDate = new DateTime(1967, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "RETIRED",
                            CurrentRank = "CPT",
                            PersonId = 4
                        },
                        new
                        {
                            Id = 4,
                            CareerEndDate = new DateTime(1966, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CareerStartDate = new DateTime(1960, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "RETIRED",
                            CurrentRank = "1LT",
                            PersonId = 5
                        });
                });

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDuty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DutyEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DutyStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DutyTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("AstronautDuty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DutyStartDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Commander",
                            PersonId = 1,
                            Rank = "1LT"
                        },
                        new
                        {
                            Id = 2,
                            DutyEndDate = new DateTime(1966, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1962, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Pilot",
                            PersonId = 3,
                            Rank = "1LT"
                        },
                        new
                        {
                            Id = 3,
                            DutyEndDate = new DateTime(1967, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1966, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Command Pilot",
                            PersonId = 3,
                            Rank = "CPT"
                        },
                        new
                        {
                            Id = 4,
                            DutyEndDate = new DateTime(1969, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1967, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Command Module Pilot",
                            PersonId = 3,
                            Rank = "MAJ"
                        },
                        new
                        {
                            Id = 5,
                            DutyEndDate = new DateTime(1983, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1969, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Commander",
                            PersonId = 3,
                            Rank = "LCL"
                        },
                        new
                        {
                            Id = 6,
                            DutyEndDate = new DateTime(1967, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1962, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Pilot",
                            PersonId = 4,
                            Rank = "1LT"
                        },
                        new
                        {
                            Id = 7,
                            DutyEndDate = new DateTime(1969, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1967, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Command Module Pilot",
                            PersonId = 4,
                            Rank = "CPT"
                        },
                        new
                        {
                            Id = 8,
                            DutyEndDate = new DateTime(1966, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1960, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Command Pilot",
                            PersonId = 5,
                            Rank = "1LT"
                        },
                        new
                        {
                            Id = 9,
                            DutyStartDate = new DateTime(1969, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "RETIRED",
                            PersonId = 4,
                            Rank = "CPT"
                        },
                        new
                        {
                            Id = 10,
                            DutyStartDate = new DateTime(1966, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "RETIRED",
                            PersonId = 5,
                            Rank = "1LT"
                        });
                });

            modelBuilder.Entity("StargateAPI.Business.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane Doe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "John Young"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Michael Collins"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Virgil Grissom"
                        });
                });

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDetail", b =>
                {
                    b.HasOne("StargateAPI.Business.Data.Person", "Person")
                        .WithOne("AstronautDetail")
                        .HasForeignKey("StargateAPI.Business.Data.AstronautDetail", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDuty", b =>
                {
                    b.HasOne("StargateAPI.Business.Data.Person", "Person")
                        .WithMany("AstronautDuties")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StargateAPI.Business.Data.Person", b =>
                {
                    b.Navigation("AstronautDetail");

                    b.Navigation("AstronautDuties");
                });
#pragma warning restore 612, 618
        }
    }
}
